#!/bin/sh /etc/rc.common
# Copyright (C) 2026 ARK Router Project

START=95
STOP=10
USE_PROCD=1

PROG=/usr/sbin/ark-autowan-daemon

start_service() {
	local enabled="$(uci -q get network.autowan.enabled || echo 0)"
	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	rm -f /var/run/ark-autowan.state 2>/dev/null || true
}
